[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/nord.toml"]

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"
# for undercurl in nvim, Smulx=\E[4:%p1%dm property must be added to terminfo

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2  # decrease/increase vertical line spacing between lines (integer)

[keyboard]
bindings = [
  { chars = "\u001B[13;2u", key = "Return", mods = "Shift" },
  { chars = "\u001B[13;2u", key = "Return", mods = "Shift" },
  { chars = "\u001B[13;5u", key = "Return", mods = "Control" },
  { chars = "\u001B[32;2u", key = "Space", mods = "Shift" },
  { chars = "\u001B[32;5u", key = "Space", mods = "Control" },
  { chars = "\u001B[59;5u", key = ";", mods = "Control" },
  # map <c-bs> to <c-w> to get the same experience in vim/nvim
  { chars = "\u0017", key = "Back", mods = "Control" },
  # { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Space", mods = "Shift|Control", mode = "~Search", action = "ToggleViMode" },
]

[scrolling]
history = 10000

[terminal]
shell = "/bin/bash"

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Maximized"
